#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 10 14:18:25 2019

@author: mrodgers
"""

class A:
    
    def run(self):
        print(10)
        
    def main(self):
        mjr = A()
        mjr.run()
        
mjr = A()
mjr.main()